name: vasttrafik_nara
description: Another Västtrafik travel planner

publish_to: "none"

version: 2.3.0+36

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_typeahead: ^5.0.2
  device_info_plus: ^12.2.0
  geolocator: ^14.0.2
  icons_launcher: ^3.0.3
  mixpanel_flutter: ^2.4.4
  url_launcher: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  flutter_map_location_marker: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

# flutter pub run icons_launcher:create
icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
      image_path: "assets/mac_app_icon.png"
